apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: swr.cn-east-3.myhuaweicloud.com/a42/backend:v1
        imagePullPolicy: IfNotPresent  # 逻辑校验：如果本地有就用本地，没有再去拉
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  annotations:
    kubernetes.io/elb.class: union  # 逻辑校验：写在这里，本地引擎会忽略它，但华为 CCE 的控制器会捕捉它来创建 ELB
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 5000