server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # 代理转发到后端容器
    location /api/ {
        proxy_pass http://backend:5000;
    }
}